/**
 * FILE: CommandMessage.proto
 * BRIEF: Command messages are used to send commands to any boards. These messages are sent from the ground to the rocket.
 * AUTHOR: Christopher Chan (cjchanx)
 */
syntax = "proto3";
package Proto;
import "CoreProto.proto";

/* Command Message ------------------------------------------------------------------*/
/* This acts as the command wrapper message for all SOAR Command Messages. This message is used to send commands to any board.
 *
 * The message path is defined by the source and target fields. The source field is the node that sent the message, the target field is the node that the message is intended for.
 * If the target field is set to NODE_ANY, then the message is a broadcast message and should be sent to all nodes.
 *
 * Note that all Command Messages should be ACKed by the target node. If the target node does not ACK the message, the source node should resend the message.
 */
message CommandMessage {
    // Message Path
    Node source = 1; // This is the source of the message (the node that sent the message)
    Node target = 2; // This is the destination of the message, if this is a broadcast message, this should be set to NODE_ANY

    /* There are much more robust RDT implementations, but for simplicity, we will use a sequence number simply to verify
     * ACKs are for the correct respective message. Each SOURCE node maintains a counting UINT32_T that is incremented for EVERY
     * message send to ANY source (if we want to make this more robust, we can use a unique sequence number per message path but that
     * would require an N_NODES array of sequence numbers which is not necessary for our purposes).
     */
    uint32 source_sequence_num = 3; // This is the sequence number of the message, should start at (1), if its 0 it does not need to be ACKed (ie. Non-essential Telemetry)
    

    // Message Data
    oneof message {
        // Command Messages
        FcbCommand fcb_command = 4;
        PbbCommand pbb_command = 5;
        FsbCommand fsb_command = 6;
        LrbCommand lrb_command = 7;
    }

}

message FcbCommand {
    enum Command {
        
        RSC_FIRST_INVALID = 0;

        //-- PRE-IGNITION and RECOVERY --
        RSC_ANY_TO_ABORT = 1;       // Transition to ABORT state - available from all states except for IGNITION/LAUNCH/BURN
        RSC_OPEN_VENT = 2;   // Open the vent valve
        RSC_CLOSE_VENT = 3;  // Close the vent valve
        RSC_OPEN_DRAIN = 4; // Open the drain valve
        RSC_CLOSE_DRAIN = 5; // Close the drain valve
        RSC_MEV_CLOSE = 6;   // Forces MEV to close - ONLY supported in states where it is safe to close the MEV

        //-- PRELAUNCH --
        RSC_GOTO_FILL = 7; // Transition to the FILL state

        //-- FILL --
        RSC_ARM_CONFIRM_1 = 8;   // Enable first ARM confirmation flag
        RSC_ARM_CONFIRM_2 = 9;   // Enable second ARM confirmation flag
        RSC_GOTO_ARM = 10;      // Transition to the ARM state (not allowed without the confirm flags set)
        RSC_GOTO_PRELAUNCH = 11; // Transition to the PRELAUNCH state from FILL

        //-- ARM/IGNITION/LAUNCH/BURN --

        //-- ARM --
        // DEPRACTED Power Transitions for Aegis
        // RSC_POWER_TRANSITION_ONBOARD = 12;      // Change power source to onboard
        // RSC_POWER_TRANSITION_EXTERNAL = 13;     // Change power source to external power
        // RSC_GOTO_FILL, // Transition back
        RSC_GOTO_IGNITION = 12; // Ready for ignition sequence - Transition to IGNITION state

        //-- IGNITION --
        RSC_IGNITION_TO_LAUNCH = 13;   // Confirm igniter actuation - Transition to LAUNCH state (MEV OPEN)
        // RSC_GOTO_ARM      // Non-confirm igniter actuation - Transition back to ARM state   

        //-- LAUNCH --
        // * These flight sequence commands can be replaced with direct calls to transition state IF possible
        RSC_LAUNCH_TO_BURN = 14; // Internal command, should not be triggered externally
        
        //-- BURN --
        RSC_BURN_TO_COAST = 15; // Internal command, should not be triggered externally
        
        //-- COAST --
        RSC_COAST_TO_BRAKING = 16; // Internal command, should not be triggered externally
        RSC_COAST_TO_DESCENT = 17; // Skip braking if rocket is undershooting its target apogee

        //-- DESCENT --
        RSC_BRAKING_TO_DESCENT = 18; // Internal command, should not be triggered externally

        //-- TOUCHDOWN --
        RSC_DESCENT_TO_TOUCHDOWN = 19; // Internal command, should not be triggered externally

        //-- GENERAL --
        RSC_MANUAL_IGNITION_CONFIRMED = 20; // NOTE: THIS IS UNUSED WHEN IGNITION SEQUENCE IS BYPASSED, we use the RSC_IGNITION_TO_LAUNCH command instead

        //-- TEST --
        RSC_GOTO_TEST = 21;
    //    RSC_MEV_CLOSE;
        RSC_TEST_MEV_OPEN = 22;
        RSC_TEST_MEV_ENABLE = 23;
        RSC_TEST_MEV_DISABLE = 24;

        //-- TECHNICAL --
        RSC_NONE = 25;   // Invalid command, must be last

        // TODO NEW : ADD NEW COMMANDS FOR HEATER? OR AIRBRAKES AND STUFF. OR CREATE A NEW MESSAGE TYPE FOR NON-FLIGHT-SEQUENCE COMMANDS?
    }
    
    Command command_enum = 1;
}

message PbbCommand {
    enum Command {
        PBB_NONE = 0;

        PBB_OPEN_MEV = 1;
        PBB_CLOSE_MEV = 2;

        PBB_OPEN_DRAIN = 3;
        PBB_CLOSE_DRAIN = 4;

        PBB_LAST = 5;
    }
    
    Command command_enum = 1;
}

// Not used in GUI V2
message LrbCommand {
    enum Command {
        
        LRB_NONE = 0;
        
        LRB_TARE_LOAD_CELL = 1;
        LRB_CALIBRATE_LOAD_CELL = 2;

        LRB_LAST = 3;
    }
    
    Command command_enum = 1;
    int32 command_param = 2; //for mass calibration
}

message FsbCommand {
    enum Command {
        FSB_NONE = 0;

        FSB_OPEN_AC1 = 3;
        FSB_CLOSE_AC1 = 4;
        FSB_OPEN_AC2 = 5;   // Unused
        FSB_CLOSE_AC2 = 6;  // Unused

        // FSB Valve Controls
        FSB_OPEN_PBV1 = 7; 
        FSB_CLOSE_PBV1 = 8;
        FSB_OPEN_PBV2 = 9;
        FSB_CLOSE_PBV2 = 10;
        FSB_OPEN_PBV3 = 11;
        FSB_CLOSE_PBV3 = 12;
        FSB_OPEN_PBV4 = 13;
        FSB_CLOSE_PBV4 = 14;

        // FSB Solenoid Controls
        FSB_OPEN_SOL5 = 21;
        FSB_CLOSE_SOL5 = 22;
        FSB_OPEN_SOL6 = 23;
        FSB_CLOSE_SOL6 = 24;
        FSB_OPEN_SOL7 = 25;
        FSB_CLOSE_SOL7 = 26;
        FSB_OPEN_SOL8A = 27;
        FSB_CLOSE_SOL8A = 28;
        FSB_OPEN_SOL8B = 29;
        FSB_CLOSE_SOL8B = 30;

        // FSB LOAD CELL Control (Not used in GUI V2)
        FSB_TARE_NOS1_LOAD_CELL = 33;
        FSB_TARE_NOS2_LOAD_CELL = 34;
        FSB_CALIBRATE_NOS1_LOAD_CELL = 35;
        FSB_CALIBRATE_NOS2_LOAD_CELL = 36;

        // FSB PAD BOX Control
        FSB_IGNITE_PAD_BOX1 = 31;
        FSB_IGNITE_PAD_BOX2 = 32;
        FSB_KILL_PAD_BOX1 = 37;
        FSB_KILL_PAD_BOX2 = 38;

        FSB_LAST = 39;
    }
    
    Command command_enum = 1;
    int32 command_param = 2; //for mass calibration
}