/**
 * FILE: Core.proto
 * BRIEF: Main protocol file for the SOAR Avionics System, any shared enums or messages should be defined here.
 * AUTHOR: Christopher Chan (cjchanx)
 */
syntax = "proto3";
package Proto;

/* Universal Enums ------------------------------------------------------------------*/

/* These are the nodes in the SOAR Avionics System.
 * The values are used to identify the source or destination of a message.
*/
enum Node {
    NODE_INVALID = 0;
    
    NODE_UNKNOWN = 1;   // This can happen if the node is not yet known at this stage, eg. COBS decode failed
    NODE_ANY = 2;
    NODE_FSB = 3;
    NODE_FCB = 4;
    NODE_PBB = 5;
    NODE_LRB = 6;
}

enum MessageID {
    MSG_INVALID = 0;

    MSG_UNKNOWN = 1;    // This can happen if the message ID is not yet known at this stage, eg. COBS decode failed
    MSG_CONTROL = 2;
    MSG_COMMAND = 3;
    MSG_TELEMETRY = 4;

    MSG_MAX_INVALID = 5;
}

/* Board Specific Enums ------------------------------------------------------------------*/

enum RocketState { 

        //-- GROUND --
        // Manual venting allowed at all times
        RS_PRELAUNCH = 0;   // Idle state, waiting for command to proceeding sequences
        RS_FILL = 1;
       	// N2 Prefill/Purge/Leak-check/Load-cell Tare check sub-sequences, full control of valves (except MEV) allowed
        RS_ARM = 2;         	// We don't allow fill etc. 1-2 minutes before launch : Cannot fill rocket with N2 etc. unless you return to FILL
                            // Power Transition, Fill-Arm Disconnect Sub-sequences (you should be able to revert the power transition)

        //-- IGNITION -- Manual venting NOT ALLOWED
        RS_IGNITION = 3;   	// Ignition of the ignitors
        RS_LAUNCH = 4;      	// Launch triggered by confirmation of ignition (from ignitor) is nominal : MEV Open Sequence

        //-- BURN --
        // Vents should stay closed, manual venting NOT ALLOWED
        // ! Vents open is definitely not ideal for abort! Best to keep it closed with manual override if we fail here
        // (can we maybe have the code change the true default state by overwriting EEPROM?)
        // Ideally we don't want to EVER exceed 7 seconds of burn time (we should store this time at the very least - split into 1 sub-stage for each second if necessary).
        // For timing we want ~1/10th of a second or better.
        RS_BURN = 5;        	// Main burn (vents closed MEV open) - Transition to coast based on timer


        //-- COAST --
        // Manual venting NOT ALLOWED -- Note: MEV never closes!
        RS_COAST = 6;       	// Coasting (MEV open, vents closed) - Transition to Braking, dependant on DAQ board running the altitude algorithm

        RS_BRAKING = 7;		// Air Brakes Open - Transition to Descent after apogee event

        //-- DESCENT / POSTAPOGEE --
        RS_DESCENT = 8;  		// Vents open (well into the descent)
        RS_TOUCHDOWN = 9;  		// Vents open, transmit all data over radio and accept vent commands
                        // Supports general commands (e.g. venting) and logs/transmits slowly (maybe stop logging after close to full memory?)

        //-- RECOVERY / TECHNICAL --
        RS_ABORT = 10;       	// Abort sequence, vents open, MEV closed, ignitors off
        RS_TEST = 11;      	// Test, between ABORT and PRE-LAUNCH, has full control of all GPIOs

        RS_NONE = 12;         	// Invalid state, must be last

    }