# FILE: ProtoPath.py
# BRIEF: Helpers for loading protobuf modules generated by the SoarCommunications submodule.

import sys
from pathlib import Path


def get_proto_python_path() -> Path:
    """
    Return the generated Python protobuf directory from the SoarCommunications submodule.
    """
    for parent in Path(__file__).resolve().parents:
        proto_path = parent / "SoarCommunications" / "SoarProto" / "Aegis" / "_Python"
        if proto_path.is_dir():
            return proto_path

    raise FileNotFoundError("SoarCommunications/SoarProto/Aegis/_Python was not found")


def ensure_proto_python_path() -> Path:
    """
    Add the generated protobuf directory to sys.path so generated imports resolve.
    """
    proto_path = get_proto_python_path()
    proto_path_str = str(proto_path)
    if proto_path_str not in sys.path:
        sys.path.insert(0, proto_path_str)
    return proto_path
